#!/usr/bin/env python3
"""
获取GitHub周榜项目（Weekly Trending）
"""

import requests
from datetime import datetime, timedelta
import json


# 简单的中英文翻译映射
TRANSLATIONS = {
    # 项目类型
    "ai": "AI",
    "machine-learning": "机器学习",
    "deep-learning": "深度学习",
    "llm": "大语言模型",
    "gpt": "GPT",
    "transformer": "Transformer",
    "neural-network": "神经网络",
    "nlp": "自然语言处理",
    "computer-vision": "计算机视觉",
    "diffusion": "扩散模型",

    # 工具类型
    "cli": "命令行工具",
    "api": "API",
    "framework": "框架",
    "library": "库",
    "tool": "工具",
    "editor": "编辑器",
    "dashboard": "仪表盘",
    "bot": "机器人",
    "web": "网页",
    "mobile": "移动应用",

    # 功能描述
    "fast": "快速",
    "simple": "简单",
    "powerful": "强大",
    "awesome": "优秀",
    "cool": "酷",
    "new": "新",
    "open-source": "开源",
    "free": "免费",
    "lightweight": "轻量级",
    "lightweight": "轻量级",
    "modern": "现代",
    "minimal": "极简",
    "elegant": "优雅",
    "beautiful": "美观",
    "efficient": "高效",
    "smart": "智能",
    "automated": "自动化",
    "self-hosted": "自托管",
    "local": "本地",
    "online": "在线",
    "real-time": "实时",
    "batch": "批量",
    "multi": "多",
    "cross-platform": "跨平台",
    "plugin": "插件",
    "extension": "扩展",
    "integration": "集成",
    "deployment": "部署",
    "monitoring": "监控",
    "testing": "测试",
    "debugging": "调试",
    "analysis": "分析",
    "visualization": "可视化",
    "generation": "生成",
    "detection": "检测",
    "classification": "分类",
    "prediction": "预测",
    "recommendation": "推荐",
    "search": "搜索",
    "chat": "聊天",
    "assistant": "助手",
    "copilot": "副驾驶",
    "agent": "智能体",
    "workflow": "工作流",
    "pipeline": "流水线",
    "engine": "引擎",
    "runtime": "运行时",
    "compiler": "编译器",
    "interpreter": "解释器",
    "server": "服务器",
    "client": "客户端",
    "database": "数据库",
    "cache": "缓存",
    "queue": "队列",
    "message": "消息",
    "notification": "通知",
    "security": "安全",
    "auth": "认证",
    "permission": "权限",
    "user": "用户",
    "admin": "管理",
    "config": "配置",
    "setting": "设置",
    "template": "模板",
    "scaffold": "脚手架",
    "boilerplate": "模板",
    "starter": "入门",
    "demo": "演示",
    "example": "示例",
    "tutorial": "教程",
    "documentation": "文档",
    "guide": "指南",
    "book": "书籍",
    "course": "课程",
    "video": "视频",
    "audio": "音频",
    "image": "图像",
    "text": "文本",
    "data": "数据",
    "model": "模型",
    "training": "训练",
    "inference": "推理",
    "evaluation": "评估",
    "benchmark": "基准测试",
    "dataset": "数据集",
    "corpus": "语料库",
    "vocabulary": "词汇表",
    "embedding": "嵌入",
    "attention": "注意力",
    "layer": "层",
    "network": "网络",
    "architecture": "架构",
    "optimizer": "优化器",
    "loss": "损失",
    "gradient": "梯度",
    "backpropagation": "反向传播",
    "regularization": "正则化",
    "dropout": "Dropout",
    "batch-normalization": "批归一化",
    "activation": "激活",
    "relu": "ReLU",
    "sigmoid": "Sigmoid",
    "softmax": "Softmax",
    "cross-entropy": "交叉熵",
    "mean-squared-error": "均方误差",
    "accuracy": "准确率",
    "precision": "精确率",
    "recall": "召回率",
    "f1-score": "F1分数",
    "confusion-matrix": "混淆矩阵",
    "roc-curve": "ROC曲线",
    "auc": "AUC",
    "overfitting": "过拟合",
    "underfitting": "欠拟合",
    "generalization": "泛化",
    "validation": "验证",
    "cross-validation": "交叉验证",
    "hyperparameter": "超参数",
    "grid-search": "网格搜索",
    "random-search": "随机搜索",
    "bayesian-optimization": "贝叶斯优化",
    "transfer-learning": "迁移学习",
    "fine-tuning": "微调",
    "pre-training": "预训练",
    "few-shot": "少样本",
    "zero-shot": "零样本",
    "one-shot": "单样本",
    "data-augmentation": "数据增强",
    "ensemble": "集成",
    "bagging": "Bagging",
    "boosting": "Boosting",
    "random-forest": "随机森林",
    "gradient-boosting": "梯度提升",
    "xgboost": "XGBoost",
    "lightgbm": "LightGBM",
    "catboost": "CatBoost",
    "svm": "支持向量机",
    "decision-tree": "决策树",
    "k-nearest-neighbors": "K近邻",
    "naive-bayes": "朴素贝叶斯",
    "linear-regression": "线性回归",
    "logistic-regression": "逻辑回归",
    "clustering": "聚类",
    "k-means": "K均值",
    "dbscan": "DBSCAN",
    "hierarchical-clustering": "层次聚类",
    "dimensionality-reduction": "降维",
    "pca": "PCA",
    "tsne": "t-SNE",
    "umap": "UMAP",
    "anomaly-detection": "异常检测",
    "time-series": "时间序列",
    "forecasting": "预测",
    "recommendation-system": "推荐系统",
    "collaborative-filtering": "协同过滤",
    "content-based-filtering": "基于内容过滤",
    "reinforcement-learning": "强化学习",
    "q-learning": "Q学习",
    "deep-q-network": "DQN",
    "policy-gradient": "策略梯度",
    "actor-critic": "演员-评论家",
    "monte-carlo-tree-search": "蒙特卡洛树搜索",
    "generative-adversarial-network": "生成对抗网络",
    "variational-autoencoder": "变分自编码器",
    "autoencoder": "自编码器",
    "recurrent-neural-network": "循环神经网络",
    "long-short-term-memory": "长短时记忆",
    "gated-recurrent-unit": "门控循环单元",
    "convolutional-neural-network": "卷积神经网络",
    "resnet": "ResNet",
    "vgg": "VGG",
    "inception": "Inception",
    "efficientnet": "EfficientNet",
    "mobilenet": "MobileNet",
    "yolo": "YOLO",
    "ssd": "SSD",
    "faster-rcnn": "Faster R-CNN",
    "mask-rcnn": "Mask R-CNN",
    "unet": "U-Net",
    "bert": "BERT",
    "gpt-2": "GPT-2",
    "gpt-3": "GPT-3",
    "gpt-4": "GPT-4",
    "llama": "LLaMA",
    "llama-2": "LLaMA 2",
    "mistral": "Mistral",
    "falcon": "Falcon",
    "vicuna": "Vicuna",
    "alpaca": "Alpaca",
    "dolly": "Dolly",
    "flan": "FLAN",
    "t5": "T5",
    "bart": "BART",
    "pegasus": "Pegasus",
    "blender": "Blender",
    "dall-e": "DALL-E",
    "stable-diffusion": "Stable Diffusion",
    "midjourney": "Midjourney",
    "whisper": "Whisper",
    "chatgpt": "ChatGPT",
    "claude": "Claude",
    "gemini": "Gemini",
    "palm": "PaLM",
    "bard": "Bard",
    "copilot": "Copilot",
    "codex": "Codex",
    "davinci": "DaVinci",
    "curie": "Curie",
    "babbage": "Babbage",
    "ada": "Ada",
    "text-davinci": "Text-DaVinci",
    "code-davinci": "Code-DaVinci",
    "gpt-3.5": "GPT-3.5",
    "gpt-4-turbo": "GPT-4 Turbo",
    "gpt-4o": "GPT-4o",
    "gpt-4-vision": "GPT-4 Vision",
    "gpt-4-all": "GPT-4 All",
    "chatgpt-api": "ChatGPT API",
    "openai-api": "OpenAI API",
    "anthropic-api": "Anthropic API",
    "google-ai": "Google AI",
    "microsoft-ai": "Microsoft AI",
    "meta-ai": "Meta AI",
    "nvidia-ai": "NVIDIA AI",
    "amazon-ai": "Amazon AI",
    "ibm-ai": "IBM AI",
    "salesforce-ai": "Salesforce AI",
    "hugging-face": "Hugging Face",
    "tensorflow": "TensorFlow",
    "pytorch": "PyTorch",
    "keras": "Keras",
    "scikit-learn": "Scikit-learn",
    "pandas": "Pandas",
    "numpy": "NumPy",
    "scipy": "SciPy",
    "matplotlib": "Matplotlib",
    "seaborn": "Seaborn",
    "plotly": "Plotly",
    "dash": "Dash",
    "streamlit": "Streamlit",
    "gradio": "Gradio",
    "flask": "Flask",
    "django": "Django",
    "fastapi": "FastAPI",
    "express": "Express",
    "nextjs": "Next.js",
    "react": "React",
    "vue": "Vue",
    "angular": "Angular",
    "svelte": "Svelte",
    "typescript": "TypeScript",
    "javascript": "JavaScript",
    "python": "Python",
    "rust": "Rust",
    "go": "Go",
    "java": "Java",
    "c++": "C++",
    "c": "C",
    "swift": "Swift",
    "kotlin": "Kotlin",
    "ruby": "Ruby",
    "php": "PHP",
    "sql": "SQL",
    "html": "HTML",
    "css": "CSS",
    "sass": "Sass",
    "less": "Less",
    "tailwind": "Tailwind",
    "bootstrap": "Bootstrap",
    "material-ui": "Material UI",
    "ant-design": "Ant Design",
    "chakra-ui": "Chakra UI",
    "styled-components": "Styled Components",
    "emotion": "Emotion",
    "redux": "Redux",
    "mobx": "MobX",
    "zustand": "Zustand",
    "jotai": "Jotai",
    "recoil": "Recoil",
    "context": "Context",
    "hooks": "Hooks",
    "state-management": "状态管理",
    "routing": "路由",
    "navigation": "导航",
    "authentication": "认证",
    "authorization": "授权",
    "oauth": "OAuth",
    "jwt": "JWT",
    "session": "会话",
    "cookie": "Cookie",
    "local-storage": "本地存储",
    "indexeddb": "IndexedDB",
    "webworker": "Web Worker",
    "webassembly": "WebAssembly",
    "webgl": "WebGL",
    "canvas": "Canvas",
    "svg": "SVG",
    "animation": "动画",
    "transition": "过渡",
    "transform": "变换",
    "grid": "网格",
    "flexbox": "弹性盒子",
    "responsive": "响应式",
    "mobile-first": "移动优先",
    "desktop-first": "桌面优先",
    "dark-mode": "暗黑模式",
    "light-mode": "亮色模式",
    "theme": "主题",
    "customization": "自定义",
    "localization": "本地化",
    "i18n": "国际化",
    "a11y": "无障碍",
    "accessibility": "可访问性",
    "seo": "SEO",
    "performance": "性能",
    "optimization": "优化",
    "lazy-loading": "懒加载",
    "code-splitting": "代码分割",
    "tree-shaking": "树摇",
    "minification": "压缩",
    "bundling": "打包",
    "transpilation": "转译",
    "compilation": "编译",
    "interpretation": "解释",
    "debugging": "调试",
    "testing": "测试",
    "unit-testing": "单元测试",
    "integration-testing": "集成测试",
    "e2e-testing": "端到端测试",
    "snapshot-testing": "快照测试",
    "mocking": "模拟",
    "coverage": "覆盖率",
    "ci-cd": "CI/CD",
    "devops": "DevOps",
    "docker": "Docker",
    "kubernetes": "Kubernetes",
    "aws": "AWS",
    "azure": "Azure",
    "gcp": "GCP",
    "heroku": "Heroku",
    "vercel": "Vercel",
    "netlify": "Netlify",
    "cloudflare": "Cloudflare",
    "firebase": "Firebase",
    "supabase": "Supabase",
    "mongodb": "MongoDB",
    "postgresql": "PostgreSQL",
    "mysql": "MySQL",
    "redis": "Redis",
    "elasticsearch": "Elasticsearch",
    "sqlite": "SQLite",
    "prisma": "Prisma",
    "typeorm": "TypeORM",
    "sequelize": "Sequelize",
    "mongoose": "Mongoose",
    "graphql": "GraphQL",
    "rest": "REST",
    "grpc": "gRPC",
    "websocket": "WebSocket",
    "http": "HTTP",
    "https": "HTTPS",
    "tcp": "TCP",
    "udp": "UDP",
    "ip": "IP",
    "dns": "DNS",
    "cdn": "CDN",
    "ssl": "SSL",
    "tls": "TLS",
    "ssh": "SSH",
    "ftp": "FTP",
    "smtp": "SMTP",
    "imap": "IMAP",
    "pop3": "POP3",
    "mqtt": "MQTT",
    "amqp": "AMQP",
    "kafka": "Kafka",
    "rabbitmq": "RabbitMQ",
    "celery": "Celery",
    "bull": "Bull",
    "agenda": "Agenda",
    "node-schedule": "Node Schedule",
    "cron": "Cron",
    "scheduler": "调度器",
    "job": "任务",
    "queue": "队列",
    "worker": "工作进程",
    "producer": "生产者",
    "consumer": "消费者",
    "publisher": "发布者",
    "subscriber": "订阅者",
    "observer": "观察者",
    "mediator": "中介者",
    "strategy": "策略",
    "factory": "工厂",
    "singleton": "单例",
    "builder": "建造者",
    "prototype": "原型",
    "adapter": "适配器",
    "decorator": "装饰器",
    "facade": "外观",
    "proxy": "代理",
    "chain": "责任链",
    "command": "命令",
    "iterator": "迭代器",
    "state": "状态",
    "memento": "备忘录",
    "visitor": "访问者",
    "interpreter": "解释器",
    "template-method": "模板方法",
    "composite": "组合",
    "flyweight": "享元",
    "bridge": "桥接",
    "abstract-factory": "抽象工厂",
    "method-chaining": "方法链",
    "fluent-interface": "流式接口",
    "dependency-injection": "依赖注入",
    "inversion-of-control": "控制反转",
    "aop": "面向切面",
    "ioc": "控制反转",
    "solid": "SOLID原则",
    "dry": "DRY原则",
    "kiss": "KISS原则",
    "yagni": "YAGNI原则",
    "clean-code": "整洁代码",
    "refactoring": "重构",
    "code-review": "代码审查",
    "pair-programming": "结对编程",
    "tdd": "测试驱动开发",
    "bdd": "行为驱动开发",
    "atdd": "验收测试驱动开发",
    "specification": "规格说明",
    "acceptance": "验收",
    "behavior": "行为",
    "unit": "单元",
    "integration": "集成",
    "system": "系统",
    "acceptance": "验收",
    "regression": "回归",
    "smoke": "冒烟",
    "sanity": "健全性",
    "stress": "压力",
    "load": "负载",
    "performance": "性能",
    "security": "安全",
    "penetration": "渗透",
    "vulnerability": "漏洞",
    "exploit": "利用",
    "attack": "攻击",
    "defense": "防御",
    "protection": "保护",
    "firewall": "防火墙",
    "encryption": "加密",
    "decryption": "解密",
    "hash": "哈希",
    "checksum": "校验和",
    "signature": "签名",
    "certificate": "证书",
    "key": "密钥",
    "token": "令牌",
    "password": "密码",
    "secret": "秘密",
    "credential": "凭据",
    "identity": "身份",
    "authentication": "认证",
    "authorization": "授权",
    "permission": "权限",
    "role": "角色",
    "user": "用户",
    "group": "组",
    "organization": "组织",
    "tenant": "租户",
    "workspace": "工作区",
    "project": "项目",
    "team": "团队",
    "member": "成员",
    "admin": "管理员",
    "owner": "所有者",
    "viewer": "查看者",
    "editor": "编辑者",
    "contributor": "贡献者",
    "collaborator": "协作者",
    "guest": "访客",
    "anonymous": "匿名",
    "public": "公开",
    "private": "私有",
    "internal": "内部",
    "external": "外部",
    "shared": "共享",
    "readonly": "只读",
    "writeonly": "只写",
    "readwrite": "读写",
    "allowed": "允许",
    "denied": "拒绝",
    "blocked": "阻止",
    "banned": "禁止",
    "suspended": "暂停",
    "active": "活跃",
    "inactive": "不活跃",
    "enabled": "启用",
    "disabled": "禁用",
    "on": "开启",
    "off": "关闭",
    "true": "真",
    "false": "假",
    "yes": "是",
    "no": "否",
    "null": "空",
    "undefined": "未定义",
    "nan": "非数字",
    "inf": "无穷大",
    "-inf": "负无穷大",
    "max": "最大",
    "min": "最小",
    "sum": "求和",
    "count": "计数",
    "avg": "平均",
    "mean": "均值",
    "median": "中位数",
    "mode": "众数",
    "std": "标准差",
    "var": "方差",
    "percentile": "百分位数",
    "quartile": "四分位数",
    "range": "范围",
    "iqr": "四分位距",
    "z-score": "Z分数",
    "outlier": "异常值",
    "anomaly": "异常",
    "normal": "正态",
    "distribution": "分布",
    "histogram": "直方图",
    "boxplot": "箱线图",
    "scatter": "散点图",
    "line": "折线图",
    "bar": "柱状图",
    "pie": "饼图",
    "heatmap": "热力图",
    "contour": "等高线图",
    "surface": "曲面图",
    "3d": "3D",
    "2d": "2D",
    "1d": "1D",
    "scalar": "标量",
    "vector": "向量",
    "matrix": "矩阵",
    "tensor": "张量",
    "array": "数组",
    "list": "列表",
    "tuple": "元组",
    "dict": "字典",
    "set": "集合",
    "queue": "队列",
    "stack": "栈",
    "tree": "树",
    "graph": "图",
    "linked-list": "链表",
    "hash-map": "哈希表",
    "binary-tree": "二叉树",
    "binary-search-tree": "二叉搜索树",
    "heap": "堆",
    "priority-queue": "优先队列",
    "segment-tree": "线段树",
    "fenwick-tree": "树状数组",
    "union-find": "并查集",
    "trie": "字典树",
    "suffix-tree": "后缀树",
    "bloom-filter": "布隆过滤器",
    "hyperloglog": "HyperLogLog",
    "count-min-sketch": "Count-Min Sketch",
    "skip-list": "跳表",
    "balanced-tree": "平衡树",
    "red-black-tree": "红黑树",
    "avl-tree": "AVL树",
    "b-tree": "B树",
    "b+-tree": "B+树",
    "r-tree": "R树",
    "k-d-tree": "K-D树",
    "octree": "八叉树",
    "quadtree": "四叉树",
    "spatial-index": "空间索引",
    "geospatial": "地理空间",
    "geojson": "GeoJSON",
    "kml": "KML",
    "shapefile": "Shapefile",
    "projection": "投影",
    "coordinate": "坐标",
    "latitude": "纬度",
    "longitude": "经度",
    "altitude": "海拔",
    "elevation": "高程",
    "contour": "等高线",
    "topology": "拓扑",
    "vector": "矢量",
    "raster": "栅格",
    "pixel": "像素",
    "voxel": "体素",
    "mesh": "网格",
    "polygon": "多边形",
    "polyline": "折线",
    "point": "点",
    "line": "线",
    "circle": "圆",
    "ellipse": "椭圆",
    "rectangle": "矩形",
    "square": "正方形",
    "triangle": "三角形",
    "quadrilateral": "四边形",
    "pentagon": "五边形",
    "hexagon": "六边形",
    "octagon": "八边形",
    "polygon": "多边形",
    "convex": "凸",
    "concave": "凹",
    "simple": "简单",
    "complex": "复杂",
    "compound": "复合",
    "self-intersecting": "自相交",
    "degenerate": "退化",
    "colinear": "共线",
    "parallel": "平行",
    "perpendicular": "垂直",
    "intersecting": "相交",
    "tangent": "切线",
    "secant": "割线",
    "normal": "法线",
    "tangent-plane": "切平面",
    "curvature": "曲率",
    "torsion": "挠率",
    "arc-length": "弧长",
    "surface-area": "表面积",
    "volume": "体积",
    "centroid": "质心",
    "center-of-mass": "质心",
    "moment-of-inertia": "转动惯量",
    "radius": "半径",
    "diameter": "直径",
    "circumference": "周长",
    "perimeter": "周长",
    "area": "面积",
    "length": "长度",
    "width": "宽度",
    "height": "高度",
    "depth": "深度",
    "thickness": "厚度",
    "diagonal": "对角线",
    "edge": "边",
    "vertex": "顶点",
    "face": "面",
    "cell": "单元",
    "element": "元素",
    "node": "节点",
    "link": "连接",
    "branch": "分支",
    "leaf": "叶节点",
    "root": "根节点",
    "parent": "父节点",
    "child": "子节点",
    "sibling": "兄弟节点",
    "ancestor": "祖先",
    "descendant": "后代",
    "neighbor": "邻居",
    "adjacent": "相邻",
    "connected": "连接",
    "disconnected": "断开",
    "reachable": "可达",
    "unreachable": "不可达",
    "traversal": "遍历",
    "depth-first": "深度优先",
    "breadth-first": "广度优先",
    "in-order": "中序",
    "pre-order": "前序",
    "post-order": "后序",
    "level-order": "层序",
    "sorted": "已排序",
    "unsorted": "未排序",
    "ascending": "升序",
    "descending": "降序",
    "increasing": "递增",
    "decreasing": "递减",
    "non-decreasing": "非递减",
    "non-increasing": "非递增",
    "stable": "稳定",
    "unstable": "不稳定",
    "in-place": "原地",
    "out-of-place": "非原地",
    "adaptive": "自适应",
    "non-adaptive": "非自适应",
    "online": "在线",
    "offline": "离线",
    "internal": "内部",
    "external": "外部",
    "comparison": "比较",
    "non-comparison": "非比较",
    "integer": "整数",
    "floating-point": "浮点数",
    "string": "字符串",
    "character": "字符",
    "byte": "字节",
    "bit": "位",
    "word": "字",
    "block": "块",
    "page": "页",
    "segment": "段",
    "offset": "偏移",
    "index": "索引",
    "key": "键",
    "value": "值",
    "pair": "对",
    "entry": "条目",
    "record": "记录",
    "tuple": "元组",
    "struct": "结构体",
    "class": "类",
    "object": "对象",
    "instance": "实例",
    "method": "方法",
    "function": "函数",
    "procedure": "过程",
    "routine": "例程",
    "subroutine": "子程序",
    "coroutine": "协程",
    "generator": "生成器",
    "iterator": "迭代器",
    "closure": "闭包",
    "lambda": "匿名函数",
    "anonymous-function": "匿名函数",
    "first-class": "一等",
    "higher-order": "高阶",
    "pure": "纯",
    "impure": "非纯",
    "side-effect": "副作用",
    "stateless": "无状态",
    "stateful": "有状态",
    "mutable": "可变",
    "immutable": "不可变",
    "persistent": "持久",
    "ephemeral": "临时",
    "copy-on-write": "写时复制",
    "structural-sharing": "结构共享",
    "path-copying": "路径复制",
    "hash-array-mapped-trie": "哈希数组映射前缀树",
    "relaxed-radix-balanced": "宽松基数平衡",
    "concurrency": "并发",
    "parallelism": "并行",
    "thread": "线程",
    "process": "进程",
    "task": "任务",
    "fiber": "纤程",
    "green-thread": "绿色线程",
    "coroutine": "协程",
    "async": "异步",
    "sync": "同步",
    "await": "等待",
    "promise": "承诺",
    "future": "未来",
    "deferred": "延迟",
    "callback": "回调",
    "event-loop": "事件循环",
    "message-passing": "消息传递",
    "shared-memory": "共享内存",
    "mutex": "互斥锁",
    "semaphore": "信号量",
    "condition-variable": "条件变量",
    "barrier": "屏障",
    "lock": "锁",
    "spinlock": "自旋锁",
    "read-write-lock": "读写锁",
    "reentrant-lock": "可重入锁",
    "deadlock": "死锁",
    "livelock": "活锁",
    "starvation": "饥饿",
    "race-condition": "竞态条件",
    "atomic": "原子",
    "volatile": "易失",
    "memory-model": "内存模型",
    "cache-coherence": "缓存一致性",
    "false-sharing": "伪共享",
    "contention": "争用",
    "scalability": "可扩展性",
    "throughput": "吞吐量",
    "latency": "延迟",
    "bottleneck": "瓶颈",
    "hotspot": "热点",
    "cold-path": "冷路径",
    "warm-up": "预热",
    "jit": "JIT",
    "aot": "AOT",
    "interpreter": "解释器",
    "compiler": "编译器",
    "transpiler": "转译器",
    "linker": "链接器",
    "loader": "加载器",
    "assembler": "汇编器",
    "disassembler": "反汇编器",
    "decompiler": "反编译器",
    "debugger": "调试器",
    "profiler": "分析器",
    "tracer": "跟踪器",
    "logger": "日志器",
    "monitor": "监控器",
    "analyzer": "分析器",
    "scanner": "扫描器",
    "parser": "解析器",
    "lexer": "词法分析器",
    "tokenizer": "分词器",
    "ast": "抽象语法树",
    "ir": "中间表示",
    "bytecode": "字节码",
    "machine-code": "机器码",
    "assembly": "汇编",
    "source-code": "源代码",
    "binary": "二进制",
    "executable": "可执行文件",
    "library": "库",
    "framework": "框架",
    "runtime": "运行时",
    "vm": "虚拟机",
    "jvm": "JVM",
    "v8": "V8",
    "spidermonkey": "SpiderMonkey",
    "javascriptcore": "JavaScriptCore",
    "chakra": "Chakra",
    "dotnet": ".NET",
    "mono": "Mono",
    "coreclr": "CoreCLR",
    "il2cpp": "IL2CPP",
    "aot": "AOT",
    "tiering": "分层",
    "optimizing": "优化",
    "baseline": "基线",
    "on-stack-replacement": "栈上替换",
    "deoptimization": "反优化",
    "bailout": "退出",
    "osr": "OSR",
    "ic": "内联缓存",
    "polymorphic": "多态",
    "megamorphic": "超多态",
    "monomorphic": "单态",
    "hidden-class": "隐藏类",
    "shape": "形状",
    "map": "映射",
    "transition": "转换",
    "inline-cache": "内联缓存",
    "call-site": "调用点",
    "feedback": "反馈",
    "speculation": "推测",
    "deoptimization": "反优化",
    "osr": "栈上替换",
    "compilation": "编ilation",
    "tiering": "分层",
    "baseline": "基线",
    "optimizing": "优化",
    "turbofan": "TurboFan",
    "maglev": "Maglev",
    "sparkplug": "Sparkplug",
    "liftoff": "Liftoff",
    "wasm": "WebAssembly",
    "wasi": "WASI",
    "wasmtime": "Wasmtime",
    "wasmer": "Wasmer",
    "assemblyscript": "AssemblyScript",
    "rust-wasm": "Rust Wasm",
    "go-wasm": "Go Wasm",
    "assembly": "汇编",
    "memory": "内存",
    "linear-memory": "线性内存",
    "table": "表",
    "global": "全局",
    "import": "导入",
    "export": "导出",
    "function": "函数",
    "control-flow": "控制流",
    "block": "块",
    "loop": "循环",
    "if": "如果",
    "else": "否则",
    "br": "分支",
    "br_if": "条件分支",
    "br_table": "分支表",
    "return": "返回",
    "call": "调用",
    "call_indirect": "间接调用",
    "drop": "丢弃",
    "select": "选择",
    "typed-select": "类型化选择",
    "local.get": "获取局部变量",
    "local.set": "设置局部变量",
    "local.tee": "设置并返回",
    "global.get": "获取全局变量",
    "global.set": "设置全局变量",
    "load": "加载",
    "store": "存储",
    "memory.size": "内存大小",
    "memory.grow": "内存增长",
    "i32.const": "i32常量",
    "i64.const": "i64常量",
    "f32.const": "f32常量",
    "f64.const": "f64常量",
    "i32.add": "i32加法",
    "i32.sub": "i32减法",
    "i32.mul": "i32乘法",
    "i32.div_s": "i32有符号除法",
    "i32.div_u": "i32无符号除法",
    "i32.rem_s": "i32有符号取余",
    "i32.rem_u": "i32无符号取余",
    "i32.and": "i32与",
    "i32.or": "i32或",
    "i32.xor": "i32异或",
    "i32.shl": "i32左移",
    "i32.shr_s": "i32有符号右移",
    "i32.shr_u": "i32无符号右移",
    "i32.rotl": "i32循环左移",
    "i32.rotr": "i32循环右移",
    "i32.clz": "i32前导零",
    "i32.ctz": "i32尾随零",
    "i32.popcnt": "i32 popcount",
    "i32.eqz": "i32等于零",
    "i32.eq": "i32等于",
    "i32.ne": "i32不等于",
    "i32.lt_s": "i32有符号小于",
    "i32.lt_u": "i32无符号小于",
    "i32.gt_s": "i32有符号大于",
    "i32.gt_u": "i32无符号大于",
    "i32.le_s": "i32有符号小于等于",
    "i32.le_u": "i32无符号小于等于",
    "i32.ge_s": "i32有符号大于等于",
    "i32.ge_u": "i32无符号大于等于",
    "i32.wrap_i64": "i32包装i64",
    "i32.trunc_f32_s": "i32截断f32有符号",
    "i32.trunc_f32_u": "i32截断f32无符号",
    "i32.trunc_f64_s": "i32截断f64有符号",
    "i32.trunc_f64_u": "i32截断f64无符号",
    "i32.reinterpret_f32": "i32重新解释f32",
    "i64.extend_i32_s": "i64扩展i32有符号",
    "i64.extend_i32_u": "i64扩展i32无符号",
    "i64.trunc_f32_s": "i64截断f32有符号",
    "i64.trunc_f32_u": "i64截断f32无符号",
    "i64.trunc_f64_s": "i64截断f64有符号",
    "i64.trunc_f64_u": "i64截断f64无符号",
    "i64.reinterpret_f64": "i64重新解释f64",
    "f32.convert_i32_s": "f32转换i32有符号",
    "f32.convert_i32_u": "f32转换i32无符号",
    "f32.convert_i64_s": "f32转换i64有符号",
    "f32.convert_i64_u": "f32转换i64无符号",
    "f32.demote_f64": "f32降级f64",
    "f32.reinterpret_i32": "f32重新解释i32",
    "f64.convert_i32_s": "f64转换i32有符号",
    "f64.convert_i32_u": "f64转换i32无符号",
    "f64.convert_i64_s": "f64转换i64有符号",
    "f64.convert_i64_u": "f64转换i64无符号",
    "f64.promote_f32": "f64提升f32",
    "f64.reinterpret_i64": "f64重新解释i64",
}


def translate_to_chinese(text):
    """将英文描述翻译成中文（简单的关键词替换）"""
    if not text:
        return ""

    # 如果主要是中文，直接返回
    chinese_chars = sum(1 for c in text if '一' <= c <= '鿿')
    if chinese_chars > len(text) * 0.3:
        return text

    # 尝试进行简单翻译
    result = text.lower()

    # 按照翻译映射表进行替换（从长到短排序，避免部分匹配）
    sorted_keys = sorted(TRANSLATIONS.keys(), key=len, reverse=True)
    for key in sorted_keys:
        if key in result:
            result = result.replace(key, TRANSLATIONS[key])

    return result


def get_trending_projects(days=7, max_results=10):
    """
    获取GitHub周榜项目

    Args:
        days: 时间范围（天），默认7天（一周）
        max_results: 最多返回的项目数

    Returns:
        list: 项目列表
    """
    # 计算起始日期
    start_date = (datetime.now() - timedelta(days=days)).strftime("%Y-%m-%d")

    # GitHub API搜索接口
    # 搜索条件：最近7天内创建的，按star数排序
    url = "https://api.github.com/search/repositories"

    # 搜索参数 - 获取最近一周的热门项目
    params = {
        "q": f"created:>{start_date} stars:>20",  # 创建时间 > start_date 且 star数 > 20
        "sort": "stars",
        "order": "desc",
        "per_page": max_results
    }

    headers = {
        "Accept": "application/vnd.github.v3+json"
    }

    try:
        response = requests.get(url, params=params, headers=headers, timeout=30)
        response.raise_for_status()

        data = response.json()
        items = data.get("items", [])

        # 整理项目信息
        projects = []
        for item in items:
            # 生成中文描述
            description = item.get("description", "") or ""
            description_cn = translate_to_chinese(description)

            project = {
                "name": item.get("name", ""),
                "full_name": item.get("full_name", ""),
                "description": description if description else "No description",
                "description_cn": description_cn if description_cn != description else "",
                "stars": item.get("stargazers_count", 0),
                "forks": item.get("forks_count", 0),
                "language": item.get("language", "Unknown") or "Unknown",
                "url": item.get("html_url", ""),
                "topics": item.get("topics", [])[:5],  # 最多5个标签
                "created_at": item.get("created_at", ""),
                "owner": {
                    "login": item.get("owner", {}).get("login", ""),
                    "avatar_url": item.get("owner", {}).get("avatar_url", "")
                }
            }
            projects.append(project)

        return projects

    except requests.exceptions.RequestException as e:
        print(f"Error fetching GitHub projects: {e}")
        return []


def format_number(num):
    """格式化数字显示（如 1200 -> 1.2k）"""
    if num >= 1000:
        return f"{num / 1000:.1f}k"
    return str(num)


if __name__ == "__main__":
    # 测试使用
    projects = get_trending_projects(days=14, max_results=10)
    print(f"Found {len(projects)} trending projects:")
    for i, proj in enumerate(projects, 1):
        print(f"{i}. {proj['name']} - ⭐ {format_number(proj['stars'])}")
        print(f"   {proj['description'][:80]}...")
        print()
